Fix clippy error
Clippy is failing with a missing Default impl. I wasn't sure if this
could be derive()'d and I didn't check.

```
error: you should consider adding a `Default` implementation for `WebsocketInboundCloseMessage`
   --> src/rsgi/io.rs:292:5
    |
292 | /     pub fn new() -> Self {
293 | |         Self {
294 | |             kind: WebsocketMessageType::Close as usize,
295 | |         }
296 | |     }
    | |_____^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#new_without_default
    = note: `-D clippy::new-without-default` implied by `-D warnings`
help: try adding this
    |
291 + impl Default for WebsocketInboundCloseMessage {
292 +     fn default() -> Self {
293 +         Self::new()
294 +     }
295 + }
    |

error: could not compile `granian` (lib test) due to previous error
make: *** [Makefile:26: lint-rust] Error 101
```